// Mgmt
// Copyright (C) James Shubin and the project contributors
// Written by James Shubin <james@shubin.ca> and the project contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Additional permission under GNU GPL version 3 section 7
//
// If you modify this program, or any covered work, by linking or combining it
// with embedded mcl code and modules (and that the embedded mcl code and
// modules which link with this program, contain a copy of their source code in
// the authoritative form) containing parts covered by the terms of any other
// license, the licensors of this program grant you additional permission to
// convey the resulting work. Furthermore, the licensors of this program grant
// the original author, James Shubin, additional permission to update this
// additional permission if he deems it necessary to achieve the goals of this
// additional permission.

package corerespassword

import (
	"context"
	"fmt"

	coreres "github.com/purpleidea/mgmt/lang/core/res"
	"github.com/purpleidea/mgmt/lang/funcs"
	"github.com/purpleidea/mgmt/lang/interfaces"
	"github.com/purpleidea/mgmt/lang/types"
)

const (
	// ValueFuncName is the name this function is registered as.
	ValueFuncName = "value"

	// arg names...
	valueArgNameName = "name"
)

func init() {
	funcs.ModuleRegister(coreres.ModuleName+"/"+ModuleName, ValueFuncName, func() interfaces.Func { return &ValueFunc{} })
}

var _ interfaces.StreamableFunc = &ValueFunc{}

// ValueFunc is a function that returns the live password that was generated by
// a password resource. It takes the name of that password resource and returns
// its generated password as a string. The password resource publishes its value
// into the local Bridge API, and this function reads and watches it from there.
// Until the resource has generated (and published) a password, this function
// returns a catchable error, so that it can be used together with the except
// operator to supply a fallback value, for example:
//
//	$secret = password.value("pass0") <|> "hunter2"
type ValueFunc struct {
	interfaces.Textarea

	init *interfaces.Init

	input chan string // stream of inputs
	name  *string     // the active name

	watchChan chan struct{}
}

// String returns a simple name for this function. This is needed so this struct
// can satisfy the pgraph.Vertex interface.
func (obj *ValueFunc) String() string {
	return ValueFuncName
}

// ArgGen returns the Nth arg name for this function.
func (obj *ValueFunc) ArgGen(index int) (string, error) {
	seq := []string{valueArgNameName}
	if l := len(seq); index >= l {
		return "", fmt.Errorf("index %d exceeds arg length of %d", index, l)
	}
	return seq[index], nil
}

// sig is a helper to return the static type signature of this function.
func (obj *ValueFunc) sig() *types.Type {
	// func(name str) str
	return types.NewType(fmt.Sprintf("func(%s str) str", valueArgNameName))
}

// Validate makes sure we've built our struct properly. It is usually unused for
// normal functions that users can use directly.
func (obj *ValueFunc) Validate() error {
	return nil
}

// Info returns some static info about itself.
func (obj *ValueFunc) Info() *interfaces.Info {
	return &interfaces.Info{
		Pure: false, // depends on the local API
		Memo: false,
		Fast: false,
		Spec: false,
		Sig:  obj.sig(),
		Err:  obj.Validate(),
	}
}

// Init runs some startup code for this function.
func (obj *ValueFunc) Init(init *interfaces.Init) error {
	obj.init = init
	obj.input = make(chan string)
	obj.watchChan = make(chan struct{}) // sender closes this when Stream ends
	return nil
}

// Copy is implemented so that the type value is not lost if we copy this
// function.
func (obj *ValueFunc) Copy() interfaces.Func {
	return &ValueFunc{
		Textarea: obj.Textarea,

		init: obj.init, // likely gets overwritten anyways
	}
}

// Stream returns the changing values that this func has over time.
func (obj *ValueFunc) Stream(ctx context.Context) error {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel() // important so that we cleanup the watch when exiting
	for {
		select {
		case name, ok := <-obj.input:
			if !ok {
				obj.input = nil // don't infinite loop back
				return fmt.Errorf("unexpected close")
			}

			if obj.name != nil && *obj.name == name {
				continue // nothing changed
			}

			// We don't support changing the name over time, since
			// the watch is set up against a single resource name.
			if obj.name == nil {
				obj.name = &name // store it
				var err error
				// Don't send a value right away, wait for the
				// first BridgeWatch startup event to get one!
				obj.watchChan, err = obj.init.Local.BridgeWatch(ctx, passwordNamespace, name)
				if err != nil {
					// rare, and not even possible today
					return err
				}
				continue // we get values on the watch chan, not here!
			}

			// *obj.name != name
			return fmt.Errorf("can't change name, previously: `%s`", *obj.name)

		case _, ok := <-obj.watchChan:
			if !ok { // closed
				return nil
			}

			if err := obj.init.Event(ctx); err != nil { // send event
				return err
			}

		case <-ctx.Done():
			return nil
		}
	}
}

// Call this function with the input args and return the value if it is possible
// to do so at this time.
func (obj *ValueFunc) Call(ctx context.Context, args []types.Value) (types.Value, error) {
	if len(args) < 1 {
		return nil, fmt.Errorf("not enough args")
	}
	name := args[0].Str()
	if name == "" {
		return nil, fmt.Errorf("can't use an empty name")
	}

	// Check before we send to a chan where we'd need Stream to be running.
	if obj.init == nil {
		return nil, funcs.ErrCantSpeculate
	}

	if obj.init.Debug {
		obj.init.Logf("name: %s", name)
	}

	select {
	case obj.input <- name:
	case <-ctx.Done():
		return nil, ctx.Err()
	}

	value, err := obj.init.Local.BridgeGet(ctx, passwordNamespace, name)
	if err != nil {
		// rare, and not even possible today
		return nil, err
	}
	if value == nil {
		// The password resource hasn't generated and published a
		// password yet. This error is catchable, so that the except
		// operator can be used to supply a fallback value instead.
		return nil, interfaces.Sentinelf("no password available for `%s`", name)
	}

	password, ok := value.(string)
	if !ok {
		// programming error
		return nil, fmt.Errorf("password for `%s` was not a string", name)
	}

	return &types.StrValue{V: password}, nil
}
